/* Shared route data — used by viewroots.html (users) and admin-route-links.html (admin).
   Keep route names identical across both so admin tracking links map correctly. */
window.SHIFT_ROUTES = {

    "1st Shift": {
        "Route 1 (LONI KALBHOR)": ["Loni Gaon", "HP Pump, Loni Gaon", "Wakwasti","Manjre Farm","Shawalwadi Depot","Bhekarai Nagar","Bhaji Mandai, Hadapsar","Pune Station","Maldhakka Ambedkar Bhavan","Dapodi"],
        "Route 2 (NARAYANGAON)": ["Hotel Shravani", "Narayangaon Bus Stop", "Police Station","Manchar Market Yard","Mulewadi Road","Lohakare Hospita","Rakshewade"],
        "Route 3 (SINHAGAD ROAD)": ["Kolhewadi", "Sun City", "Warje Bridge","CNG Petrol Pump, Bavdhan","Balewadi","Dange Chowk","Chinchwad Nagar"],
        "Route 4 (WARJE)":["NDA","Mayur Colony","Ashish Garden, Kothrud"],
        "Route 5 (WAGHOLI)":["Wageshwar Mandir","Kharadi Bypass","Wadgaon Sheri, Tingre Nagar","Bhopkhel","Parande Nagar","Datta Nagar"],
        "Route 6 (KATRAJ)":["Santosh Nagar","Bharati Vidyapeeth","Hatti Chowk","Padmavati","Bibwewadi","Shaniwar Wada","Shivajinagar","Khondba Chowk"],
        "Route 7 (MENGDEWADI)": [ "Mengdewadi", "Hingewasti", "Ausari BK Bus Stand", "Pandurang Mandir", "Temkar Wasti", "Ausari KH Water Tank", "Ranwara Hotel","Shivdhan Plaza","Marathi Shala","Market Yard","Khed Bus Stand","Shiroli Phata","Rajratna Hotel"],
        "Route 8 (PABAL)":["Pabal","Petrol Pump Pabal","Tamane Mala","Kanersir","Nimgaon","Chavan Mala","Maharaja Chowk"],
        "Route 9 (VISHRANTWADI)":["Vishrantwadi Chowk","Dhanori","Kotak Mahindra","Charholi Gaon","Bank of Maharashtra","Charholi Phata","Kate Colony","Kale Colony"],
        "Route 10 (OLD SANGAVI)":["Sangavi Bus Stop","Ganpati Mandir","Kranti Chowk","Katepuram Chowk","Radha Krishna Mangal Karyalaya","Dehukar Park","Tulja Bhavani Mandir","Kalpataru Chowk","Nashik Phata","Empire Bridge","Akurdi Bajaj Gate"],
        "Route 11 (ALANDI)":["Cosmos Bank","Dehu Phata","Dudulgaon","Dudulgaon 1","Moshi","Bharat Mata Chowk","Tupe Wasti","Moshi Toll Naka","Chimbli Phata","Kuruli Phata"],
        "Route 12 (RAVET)":["Kiwale","Mukai Chowk","Adarsh Nagar","Soni Ghar","Shinde Wasti","CNG Pump"],
        "Route 13 (KALE WADI)":["Thergaon","16 No. Bus Stop","Kalewadi Bridge","Rahatani Phata","Dhangar Baba","Tapkir Chowk","Keshav Nagar Corner","Keshav Nagar Bus Stop","Talera Hospital","Chafekar Chowk","SKF Company","Prem Lok Park","Delvi Nagar"],
        "Route 14 (SHASTRI CHOWK)":["Shastri Chowk","Dighi Road","Panjar Pol","Godam Chowk","Gandharva Nagari","Sainath Hospital","Borade Wasti"],
        "Route 15 (DEHU ROAD)":["Mamurdi (Sai Nagar)","Vikas Nagar","SBI Bank","Dehu Road","Chincholi","Abhilekha Park","Sangurdi Phata","Yelwadi"],
        "Route 16 (SHEETAL BAGH)":["Landewadi","Spine Road","Jadhavwadi","Chikhli"],
        "Route 17 (WADGAON)":["Wadgaon","Matoshree","Jambhul Phata","Wadgaon Court","Chhatrapati Shivaji Chowk","Lotus","Wadgaon Phata","Murlesh Hotel","Aarth Hospital","Seva Dham","Machhi Market","Indrayani College"],
        "Route 18 (BHOSARI EXTRA)":["PMT Chowk, Bhosari","Dhawade Wasti","Satguru Nagar","Jadhavwadi","Laxmi Chowk","D Mart, Moshi","Silver 9","Rustic"],
        "Route 19 (SHARAD NAGAR)":["Sane Chowk","Sharad Nagar","Gharkul Chowk","Kaseriyo Society","Nevale Wasti","Ganesh Mandir","Navale Wasti Corner","Imperial Hospital","Talawade Chowk"],
        "Route 20 (RAJGURU NAGAR - KHED)":["Sangam Garden","Sangam Classic","Panyachi Taki","Panchayat Samiti","Chandoli Phata","Vishwakalyan"],
        "Route 21 (YCM)":["Mahesh Nagar Chowk","Nehru Nagar","Vitthal Mandir","Ajmera 1","Ajmera 2","Ajmera 3","Bajaj Colony - Amruteshwar Colony","Old RTO","Petrol Pump","Kudalwadi 1","Patil Nagar, Chikhli","Bajaj Auto"],
        "Route 22 (LINK ROAD)":["Gawade Petrol Pump","Chafekar Chowk","Bijli Nagar","Ankush Chowk","Triveni Nagar","Tawre Line","Ganesh Nagar"],
        "Route 23 (TALEGAON)":["McDonald's","Bagicha Hotel","Nim Phata","Bhandari Hospital","Kesar Hotel","Jijamata Chowk","Khadge Pump","Nagar Palika","Kaka Halwai","BSNL","Siddhi Khed","Machhi Market","Induri Gaon","Khalumbre"],
        "Route 24 (SHAHU NAGAR)":["Atal Bihari Udyan Corner","Rasrang","Ganesh Mandir","Bajaj School","Someshwar Mandir","Chintamani Corner","Kasturi Market","Polite Harmony","Ganesh International School"],
        "Route 25 (AUTO GAS TALEGAON)":["Varale Phata","Shivaji Chowk","Sindket Bank","Bullet Showroom","Balaji Marble","Aishwarya Hotel","Indori Gaon"],
        "Route 26 (WALHEKARWADI)":["Jakat Naka","Walhekarwadi Chowk","Aaher Garden","Ganpati Mandir","Gurudwara Chowk","Railway Station","Appu Ghar"],
        "Route 27 (MOHAN NAGAR)":["Pimple Saudagar","Pimpri Gaon","Kalewadi","Vijay Nagar Bus Stop","Mohan Nagar","Huma Bakery"],
        "Route 28 (BAJAJ SCHOOL)":["Vinayak Sweets","Shivalkar Chowk","Hanuman Mandir","Mehtre Garden","More Wasti","Ashtavinayak Chowk","Vande Mataram Chowk","Waghu Sane Chowk","Aishwaryam Society"],
        "Route 29 (DEHUGAON)":["Krida Sankul","Omi Home","Gatha Mandir","Arogya Hospital","Parandwal Chowk","Parishri Hotel","Omkar Society","V-Mart","Banner Bank","Vitthalwadi"],
        "Route 30 (WAKI PHATA)":["Sumbare Nagar","Ekta Nagar","Swapna Nagari","Chakan Market Yard","Yeshwant Nagar","Dnyanvardhani School","Jhipre Mala","Biradwadi"],
        "Route 31 (MEDANKARWADI)":["Kadachiwadi","Kalpataru Society","Medankarwadi Phata","Vishal Garden"],
        "Route 32 (BALAJI NAGAR CHAKAN)":["Chakan Chowk","Mutkewadi","Balaji Nagar","Premacha Chaha","IAI Company"],
        "Route 33 (CHAKAN CHOWK)":["Ambethan Chowk","Ghadge Mala","Unicare Hospital","Chakan Chowk","Arogyam Hospital","Sahara City","Kharabwadi","Mahalunge"],
        "Route 33 (DANGE CHOWK)":["Dange Chowk","Bijli Nagar","Big India","Sambhaji Chowk","Mhalsakant Chowk","TJSB Bank","Datta Wadi","Nigdi","LIC Corner","Hatti Chowk"],
        "Route 35 (NIGDI)":["Pawale Bridge","Swanand Dairy","LIC Corner","Hatti Chowk","Ganesh Nagar","Jyotiba Nagar","Talawade (Only Ladies)"],
        "Route 36 (MEDANKARWADI EXTRA)":["Kadachiwadi","Kalpataru Society","Medankarwadi Phata","Vishal Garden"],
        "Route 37 (IAI COMPANY)":["IAI Company"],
        "Route 38 (KHANDO MANDIR CHAKAN)":["Khandoba Mandir","Vishal Garden","Manik Chowk","Premacha Chaha"],
        "Route 40 (CHAKAN CHOWK)":["Ambethan Chowk","Ghadge Mala","Unicare Hospital","Chakan Chowk","Arogyam Hospital","Sahara City","Kharabwadi","Mahalunge"]
    },

    "2nd Shift": {
        "Route 1 (SINHGAD)":["Kolhewadi","Sinhagad Road","Dahyri Gaon","Navale Bridge","Warje","Bawdhan","Balewadi","Dange Chowk","Aditya Birla","Chinchwade Nagar","Kachghar Chowk","Ankush Chowk","Chakan Chowk","Bajaj Chakan"],
        "Route 2 (WAGHOLI)":["Wagholi","Vishrantwadi","Dighi","Sai Mandir","Kale Colony","Kate Colony","Chikhali","Bajaj Chakan"],
        "Route 3 (DEHU GAON)":["Krida Sankul","Gatha Mandir","V Mart","Baner Bank","Bypass Chowk","Devi Indrani","Bajaj Chakan"],
        "Route 4 (MEDANKARWADI)":["Kadachiwadi","Medankarwadi Gate","Vishal Garden","Manik Chowk","Indian Oil Pump","Balaji Nagar (Premacha Chaha)","IAI Company","Bajaj Chakan"],
        "Route 5 (WAKI PHATA)":["Biradwadi","Waki Phata","Ekta Nagar","Swapna Nagari","Market Yard","Ambethan Chowk","Zitrai Mala","Mahalunge","Bajaj Chakan"],
        "Route 6 (RAVET-WALHEKARWADI)":["Mukai Chowk","CNG Pump","Shinde Wasti","Walhekarwadi","Chintamani Chowk","Ganesh Mandir","Athurwa Park","Gurudwara Chowk","Tower Line","Huma Bakery","Bajaj Chakan"],
        "Route 7 (ALANDI)":["Charoli Phata","Dehu Phata","Dudulgaon","Moshi","Bharat Mata Chowk","Chikhali Rustic Paradise","Bajaj Chakan"],
        "Route 8 (SHASTRI CHOWK)":["Shastri Chowk","PMT Chowk","Dhawde Wasti","Godown Chowk","Panjarpol","Gandharv Nagari","Borhade Wasti","Tupe Wasti","Toll Naka","Chimbli Phata","Kurali Phata","Bajaj Chakan"],
        "Route 9 (DEHUROAD)":["Sai Nagar Mamurdi","Shinde Petrol Pump Dehuroad","Vikas Nagar Dehuroad","Bank of India Dehuroad","Mali Nagar (Malwadi)","Abhilasha Society","Mangalkaryalaya","Parandwal Chowk","Yelwadi","Bajaj Chakan"],
        "Route 10 (PIMPLE GURAV)":["Dapodi","Kate Puram Chowk","Bhau Nagar","Pimpri","Akurdi Main Gate","LIC Corner","Triveni Nagar","Bajaj Chakan"],
        "Route 11 (JADHAVWADI)":["Jadhavwadi","RTO","Sharad Nagar","Newale Wasti","Ganpati Mandir","Newale Wasti Corner","Patil Nagar","Rustic Plaza","Talwade Chowk","Mahindra Gate","Bajaj Chakan"],
        "Route 12 (TALEGAON)":["Bagicha Hotel","Tukaram Nagar","Bhandari Hospital","Bhosle Chaha","Jijamata Chowk","Khandge Petrol Pump","Kaka Halwai","BSNL","Balaji Marble","Sadumbre","Khalumbre","Bajaj Chakan"],
        "Route 13 (WADGAON)":["Chhatrapati Shivaji Chowk","Lotus","Rupesh Hotel","Athurwa Hospital","Sevadham","Indrayani College Talegaon","Bullet Showroom","Induri","Khalumbre","Bajaj Chakan"],
        "Route 14 (KHED)":["Kardewasti","Sangam Garden","Sangam Classic","Water Tank","Pabal Road","Dhadge Mala","Unicare Hospital","Arogyam Hospital","IFL City","Kharabwadi","Sara City","Mahalunge"],
        "Route 15 (KALEWADI)":["16 No Bus Stop","Kalewadi Phata","Rahatani Phata","Laxman Nagar Thergaon","Old Jakat Naka","Gawde Petrol Pump Link Road","Chafekar Chowk","Chaitanya Hall","Giriraj Housing Society","Hanuman Sweet","Mhalsakant Chowk","TJSB Bank","Axis Bank","Dattawadi","Bajaj Chakan"],
        "Route 16 (SHAHU NAGAR)":["Ajmera","Amruteshwar Colony","Shahu Garden","Aryan Residency","Ganpati Mandir","Bajaj School","Rameshwar Mandir","Sambhaji Nagar Chowk","Rajdeep Society","Kasturi Market","Shivarkar Chowk","Polite Harmony","Ganesh International School","Shine City","Bajaj Chakan"],
        "Route 17 (CHAKAN CHOWK)":["Balaji Nagar","Chakan Chowk","Ghanvat Plaza","Arogyam Hospital","Nanekarwadi","Kharabwadi","Sara City","Mahalunge","Hotel Karwa"],
        "Route 18 (MOHAN NAGAR)":["Mohan Nagar","Morewasti","Chikhali Rustic Paradise","Talwade Chowk","Mahindra Gate"],
        "Route 19 (ANKUSH CHOWK)":["Ankush Chowk","Triveni Nagar","Tower Line","Huma Bakery","Ganesh Nagar","Jotiba Nagar","Talwade Chowk"],
        "Route 20 (NARAYANGAON)":["Raut Hospital Narayangaon","Narayangaon ST Stand","Manchar Market Yard","Manchar College Road","Maxcare Hospital Manchar","Paragaon Phata","Market Yard","Ambethan Chowk"],
        "Route 21 (NIGDI)":["Big India","Dattawadi","LIC Corner","Hatti Chowk"]
    },

    "3rd Shift": {
        "Route 1 (NIGDI)":["Nigdi Bridge","LIC Chowk"],
        "Route 2 (TALEGAON)":["Talegaon","Khalumbre","Manohar Nagar Talegaon"],
        "Route 3 (DEHU GAON)":["Dehugaon","Parishree Hospital"],
        "Route 4 (SHASTRI CHOWK)":["Shastri Chowk","Bhosari","Alandi"],
        "Route 5 (RAJGURU NAGAR)":["Rajgurunagar","Khed Toll Naka","Ambethan Chowk","Biradwadi"],
        "Route 6 (MEDANKARWADI)":["Medankarwadi"],
        "Route 7 (BALAJI NAGAR)":["Balaji Nagar","Chakan","Eiffel City","Karwa Hotel"],
        "Route 8 (CHIKHALI)":["Chikhali","Sane Chowk"],
        "Route 9 (DEHUROAD)":["Dehuroad"],
        "Route 10 (PCMC)":["Mhalsakant Chowk"]
    },

    "General Shift": {
        "Route 1 (SINHGAD)":["Kolhewadi","Sinhagad Road","Dahyri Gaon","Navale Bridge","Warje","Bawdhan","Balewadi","Dange Chowk","Aditya Birla","Chinchwade Nagar","Kachghar Chowk","Ankush Chowk","Chakan Chowk","Bajaj Chakan"],
        "Route 2 (WAGHOLI)":["Wagholi","Vishrantwadi","Dighi","Sai Mandir","Kale Colony","Kate Colony","Chikhali","Bajaj Chakan"],
        "Route 3 (DEHU GAON)":["Krida Sankul","Gatha Mandir","V Mart","Baner Bank","Bypass Chowk","Devi Indrani","Bajaj Chakan"],
        "Route 4 (MEDANKARWADI)":["Kadachiwadi","Medankarwadi Gate","Vishal Garden","Manik Chowk","Indian Oil Pump","Balaji Nagar (Premacha Chaha)","IAI Company","Bajaj Chakan"],
        "Route 5 (WAKI PHATA)":["Biradwadi","Waki Phata","Ekta Nagar","Swapna Nagari","Market Yard","Ambethan Chowk","Zitrai Mala","Mahalunge","Bajaj Chakan"],
        "Route 6 (RAVET-WALHEKARWADI)":["Mukai Chowk","CNG Pump","Shinde Wasti","Walhekarwadi","Chintamani Chowk","Ganesh Mandir","Athurwa Park","Gurudwara Chowk","Tower Line","Huma Bakery","Bajaj Chakan"],
        "Route 7 (ALANDI)":["Charoli Phata","Dehu Phata","Dudulgaon","Moshi","Bharat Mata Chowk","Chikhali Rustic Paradise","Bajaj Chakan"],
        "Route 8 (SHASTRI CHOWK)":["Shastri Chowk","PMT Chowk","Dhawde Wasti","Godown Chowk","Panjarpol","Gandharv Nagari","Borhade Wasti","Tupe Wasti","Toll Naka","Chimbli Phata","Kurali Phata","Bajaj Chakan"],
        "Route 9 (DEHUROAD)":["Sai Nagar Mamurdi","Shinde Petrol Pump Dehuroad","Vikas Nagar Dehuroad","Bank of India Dehuroad","Mali Nagar (Malwadi)","Abhilasha Society","Mangalkaryalaya","Parandwal Chowk","Yelwadi","Bajaj Chakan"],
        "Route 10 (PIMPLE GURAV)":["Dapodi","Kate Puram Chowk","Bhau Nagar","Pimpri","Akurdi Main Gate","LIC Corner","Triveni Nagar","Bajaj Chakan"],
        "Route 11 (JADHAVWADI)":["Jadhavwadi","RTO","Sharad Nagar","Newale Wasti","Ganpati Mandir","Newale Wasti Corner","Patil Nagar","Rustic Plaza","Talwade Chowk","Mahindra Gate","Bajaj Chakan"],
        "Route 12 (TALEGAON)":["Bagicha Hotel","Tukaram Nagar","Bhandari Hospital","Bhosle Chaha","Jijamata Chowk","Khandge Petrol Pump","Kaka Halwai","BSNL","Balaji Marble","Sadumbre","Khalumbre","Bajaj Chakan"],
        "Route 13 (WADGAON)":["Chhatrapati Shivaji Chowk","Lotus","Rupesh Hotel","Athurwa Hospital","Sevadham","Indrayani College Talegaon","Bullet Showroom","Induri","Khalumbre","Bajaj Chakan"],
        "Route 14 (KHED)":["Kardewasti","Sangam Garden","Sangam Classic","Water Tank","Pabal Road","Dhadge Mala","Unicare Hospital","Arogyam Hospital","IFL City","Kharabwadi","Sara City","Mahalunge"],
        "Route 15 (KALEWADI)":["16 No Bus Stop","Kalewadi Phata","Rahatani Phata","Laxman Nagar Thergaon","Old Jakat Naka","Gawde Petrol Pump Link Road","Chafekar Chowk","Chaitanya Hall","Giriraj Housing Society","Hanuman Sweet","Mhalsakant Chowk","TJSB Bank","Axis Bank","Dattawadi","Bajaj Chakan"],
        "Route 16 (SHAHU NAGAR)":["Ajmera","Amruteshwar Colony","Shahu Garden","Aryan Residency","Ganpati Mandir","Bajaj School","Rameshwar Mandir","Sambhaji Nagar Chowk","Rajdeep Society","Kasturi Market","Shivarkar Chowk","Polite Harmony","Ganesh International School","Shine City","Bajaj Chakan"],
        "Route 17 (CHAKAN CHOWK)":["Balaji Nagar","Chakan Chowk","Ghanvat Plaza","Arogyam Hospital","Nanekarwadi","Kharabwadi","Sara City","Mahalunge","Hotel Karwa"],
        "Route 18 (MOHAN NAGAR)":["Mohan Nagar","Morewasti","Chikhali Rustic Paradise","Talwade Chowk","Mahindra Gate"],
        "Route 19 (ANKUSH CHOWK)":["Ankush Chowk","Triveni Nagar","Tower Line","Huma Bakery","Ganesh Nagar","Jotiba Nagar","Talwade Chowk"],
        "Route 20 (NARAYANGAON)":["Raut Hospital Narayangaon","Narayangaon ST Stand","Manchar Market Yard","Manchar College Road","Maxcare Hospital Manchar","Paragaon Phata","Market Yard","Ambethan Chowk"],
        "Route 21 (NIGDI)":["Big India","Dattawadi","LIC Corner","Hatti Chowk"]
    }
};
